apiVersion: runtimeconditions.io/binding-model/v1alpha1
kind: RuntimeConditionsBindingModel
metadata:
    semanticSha256: 5257b861f1c2e4e3e88de9dc3fd757f84fe0597753adba93dcdc359c0e1b09b1
    normalizer:
        name: rc-binding-model
        version: 0.1.0
        sha256: dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
coreProfileSchema:
    id: https://runtimeconditions.io/schemas/profile/0.1.0/runtimeconditions.profile.schema.yaml
    version: 0.1.0
    semanticSha256: 49890a0f3e7276d1e480d654176672d977df9c63094f3a24983b0a8102e1a3e3
rootExtension:
    id: urn:runtimeconditions:conformance:object-alternatives
    version: 1.0.0
    semanticSha256: 01ccacc12da88aff62243be459774d74fd29c38e4b7e25ec671a5492069b0df7
extensions:
    - id: urn:runtimeconditions:conformance:object-alternatives
      version: 1.0.0
      semanticSha256: 01ccacc12da88aff62243be459774d74fd29c38e4b7e25ec671a5492069b0df7
vocabulary:
    owners:
        - coordinate: interface:deployment:process
          category: interface
          owner: urn:runtimeconditions:conformance:object-alternatives
          kind: deployment
          interfaceType: process
        - coordinate: kind:deployment
          category: kind
          owner: urn:runtimeconditions:conformance:object-alternatives
          kind: deployment
    ownedDeclarations:
        - coordinate: kind:deployment
          owner: urn:runtimeconditions:conformance:object-alternatives
          kind: deployment
          provenance:
            owner: urn:runtimeconditions:conformance:object-alternatives
            extensionSha256: 01ccacc12da88aff62243be459774d74fd29c38e4b7e25ec671a5492069b0df7
            coordinate: kind:deployment
    interfaces:
        - coordinate: interface:deployment:process
          owner: urn:runtimeconditions:conformance:object-alternatives
          kind: deployment
          type: process
          provenance:
            owner: urn:runtimeconditions:conformance:object-alternatives
            extensionSha256: 01ccacc12da88aff62243be459774d74fd29c38e4b7e25ec671a5492069b0df7
            coordinate: interface:deployment:process
scopes:
    - coordinate: deployment:process
      kind: deployment
      interfaceType: process
      applicableSchemas:
        - urn:runtimeconditions:conformance:object-alternatives#schema:object-alternatives
      projection:
        kind: object
        required:
            - interface
        properties:
            - name: configuration
              shape:
                kind: object
                properties:
                    - name: command
                      shape:
                        kind: scalar
                        scalar: string
                        provenance:
                            owner: urn:runtimeconditions:conformance:object-alternatives
                            extensionSha256: 01ccacc12da88aff62243be459774d74fd29c38e4b7e25ec671a5492069b0df7
                            coordinate: urn:runtimeconditions:conformance:object-alternatives#schema:object-alternatives
                            jsonPointer: /properties/configuration/oneOf/0/properties/command
                      provenance:
                        owner: urn:runtimeconditions:conformance:object-alternatives
                        extensionSha256: 01ccacc12da88aff62243be459774d74fd29c38e4b7e25ec671a5492069b0df7
                        coordinate: urn:runtimeconditions:conformance:object-alternatives#schema:object-alternatives
                        jsonPointer: /properties/configuration/oneOf/0/properties/command
                    - name: image
                      shape:
                        kind: scalar
                        scalar: string
                        provenance:
                            owner: urn:runtimeconditions:conformance:object-alternatives
                            extensionSha256: 01ccacc12da88aff62243be459774d74fd29c38e4b7e25ec671a5492069b0df7
                            coordinate: urn:runtimeconditions:conformance:object-alternatives#schema:object-alternatives
                            jsonPointer: /properties/configuration/oneOf/1/properties/image
                      provenance:
                        owner: urn:runtimeconditions:conformance:object-alternatives
                        extensionSha256: 01ccacc12da88aff62243be459774d74fd29c38e4b7e25ec671a5492069b0df7
                        coordinate: urn:runtimeconditions:conformance:object-alternatives#schema:object-alternatives
                        jsonPointer: /properties/configuration/oneOf/1/properties/image
                provenance:
                    owner: urn:runtimeconditions:conformance:object-alternatives
                    extensionSha256: 01ccacc12da88aff62243be459774d74fd29c38e4b7e25ec671a5492069b0df7
                    coordinate: urn:runtimeconditions:conformance:object-alternatives#schema:object-alternatives
                    jsonPointer: /properties/configuration
              provenance:
                owner: urn:runtimeconditions:conformance:object-alternatives
                extensionSha256: 01ccacc12da88aff62243be459774d74fd29c38e4b7e25ec671a5492069b0df7
                coordinate: urn:runtimeconditions:conformance:object-alternatives#schema:object-alternatives
                jsonPointer: /properties/configuration
            - name: interface
              required: true
              shape:
                kind: object
                provenance:
                    owner: urn:runtimeconditions:conformance:object-alternatives
                    extensionSha256: 01ccacc12da88aff62243be459774d74fd29c38e4b7e25ec671a5492069b0df7
                    coordinate: urn:runtimeconditions:conformance:object-alternatives#schema:object-alternatives
                    jsonPointer: /properties/interface
              provenance:
                owner: urn:runtimeconditions:conformance:object-alternatives
                extensionSha256: 01ccacc12da88aff62243be459774d74fd29c38e4b7e25ec671a5492069b0df7
                coordinate: urn:runtimeconditions:conformance:object-alternatives#schema:object-alternatives
                jsonPointer: /properties/interface
        provenance:
            owner: urn:runtimeconditions:conformance:object-alternatives
            extensionSha256: 01ccacc12da88aff62243be459774d74fd29c38e4b7e25ec671a5492069b0df7
            coordinate: urn:runtimeconditions:conformance:object-alternatives#schema:object-alternatives
schemas:
    - coordinate: urn:runtimeconditions:conformance:object-alternatives#schema:object-alternatives
      owner: urn:runtimeconditions:conformance:object-alternatives
      id: object-alternatives
      kind: deployment
      interfaceType: process
      exact:
        additionalProperties: false
        properties:
            configuration:
                oneOf:
                    - additionalProperties: false
                      properties:
                        command:
                            type: string
                      required:
                        - command
                      type: object
                    - additionalProperties: false
                      properties:
                        image:
                            type: string
                      required:
                        - image
                      type: object
            interface:
                additionalProperties: false
                properties:
                    type:
                        const: process
                required:
                    - type
                type: object
            kind:
                const: deployment
        required:
            - interface
            - kind
        type: object
      projection:
        kind: object
        required:
            - interface
        properties:
            - name: configuration
              shape:
                kind: object
                properties:
                    - name: command
                      shape:
                        kind: scalar
                        scalar: string
                        provenance:
                            owner: urn:runtimeconditions:conformance:object-alternatives
                            extensionSha256: 01ccacc12da88aff62243be459774d74fd29c38e4b7e25ec671a5492069b0df7
                            coordinate: urn:runtimeconditions:conformance:object-alternatives#schema:object-alternatives
                            jsonPointer: /properties/configuration/oneOf/0/properties/command
                      provenance:
                        owner: urn:runtimeconditions:conformance:object-alternatives
                        extensionSha256: 01ccacc12da88aff62243be459774d74fd29c38e4b7e25ec671a5492069b0df7
                        coordinate: urn:runtimeconditions:conformance:object-alternatives#schema:object-alternatives
                        jsonPointer: /properties/configuration/oneOf/0/properties/command
                    - name: image
                      shape:
                        kind: scalar
                        scalar: string
                        provenance:
                            owner: urn:runtimeconditions:conformance:object-alternatives
                            extensionSha256: 01ccacc12da88aff62243be459774d74fd29c38e4b7e25ec671a5492069b0df7
                            coordinate: urn:runtimeconditions:conformance:object-alternatives#schema:object-alternatives
                            jsonPointer: /properties/configuration/oneOf/1/properties/image
                      provenance:
                        owner: urn:runtimeconditions:conformance:object-alternatives
                        extensionSha256: 01ccacc12da88aff62243be459774d74fd29c38e4b7e25ec671a5492069b0df7
                        coordinate: urn:runtimeconditions:conformance:object-alternatives#schema:object-alternatives
                        jsonPointer: /properties/configuration/oneOf/1/properties/image
                provenance:
                    owner: urn:runtimeconditions:conformance:object-alternatives
                    extensionSha256: 01ccacc12da88aff62243be459774d74fd29c38e4b7e25ec671a5492069b0df7
                    coordinate: urn:runtimeconditions:conformance:object-alternatives#schema:object-alternatives
                    jsonPointer: /properties/configuration
              provenance:
                owner: urn:runtimeconditions:conformance:object-alternatives
                extensionSha256: 01ccacc12da88aff62243be459774d74fd29c38e4b7e25ec671a5492069b0df7
                coordinate: urn:runtimeconditions:conformance:object-alternatives#schema:object-alternatives
                jsonPointer: /properties/configuration
            - name: interface
              required: true
              shape:
                kind: object
                provenance:
                    owner: urn:runtimeconditions:conformance:object-alternatives
                    extensionSha256: 01ccacc12da88aff62243be459774d74fd29c38e4b7e25ec671a5492069b0df7
                    coordinate: urn:runtimeconditions:conformance:object-alternatives#schema:object-alternatives
                    jsonPointer: /properties/interface
              provenance:
                owner: urn:runtimeconditions:conformance:object-alternatives
                extensionSha256: 01ccacc12da88aff62243be459774d74fd29c38e4b7e25ec671a5492069b0df7
                coordinate: urn:runtimeconditions:conformance:object-alternatives#schema:object-alternatives
                jsonPointer: /properties/interface
        provenance:
            owner: urn:runtimeconditions:conformance:object-alternatives
            extensionSha256: 01ccacc12da88aff62243be459774d74fd29c38e4b7e25ec671a5492069b0df7
            coordinate: urn:runtimeconditions:conformance:object-alternatives#schema:object-alternatives
      provenance:
        owner: urn:runtimeconditions:conformance:object-alternatives
        extensionSha256: 01ccacc12da88aff62243be459774d74fd29c38e4b7e25ec671a5492069b0df7
        coordinate: urn:runtimeconditions:conformance:object-alternatives#schema:object-alternatives
