"""Deterministic Python distribution metadata and binding resources."""

from __future__ import annotations

import json
import re
from typing import Any

import yaml

from .emitter import EmissionPlan, TypePlan
from .package import VERSION_PATTERN, fail

EMITTER_NAME = "runtimeconditions-binding-emitter"
EMITTER_VERSION = "0.1.0"
# Keep this equal to python.tools.setuptools in the shared toolchain lock.
SETUPTOOLS_VERSION = "84.0.0"


def _version(value: str, coordinate: str) -> str:
    match = VERSION_PATTERN.fullmatch(value)
    if match is None:
        fail(
            "package-config",
            "RCP1006",
            coordinate,
            f"unsupported package version {value!r}",
            "/version",
        )
    stable = ".".join(match.group(index) for index in (1, 2, 3))
    if match.group(4) is None:
        return stable
    prerelease = re.search(r"-(alpha|beta|rc)\.", value)
    assert prerelease is not None
    prefix = {"alpha": "a", "beta": "b", "rc": "rc"}[prerelease.group(1)]
    return f"{stable}{prefix}{match.group(4)}"


def _dependency_interval(value: str, coordinate: str) -> str:
    tested = _version(value, coordinate)
    major, minor, _ = (int(part) for part in value.split("-", 1)[0].split("."))
    next_breaking = f"0.{minor + 1}.0" if major == 0 else f"{major + 1}.0.0"
    return f">={tested},<{next_breaking}"


def _header(model: dict[str, Any]) -> str:
    return (
        f"# Code generated by {EMITTER_NAME} {EMITTER_VERSION} "
        f"from model {model['metadata']['semanticSha256']}; DO NOT EDIT.\n"
    )


def _pyproject(plan: EmissionPlan, model: dict[str, Any]) -> str:
    target = plan.target
    dependencies = sorted(
        target.dependencies, key=lambda item: (item.distribution_name, item.extension)
    )
    names = [item.distribution_name for item in dependencies]
    if len(names) != len(set(names)):
        fail(
            "package-config",
            "RCP1006",
            target.package_key,
            "multiple direct extensions use the same Python distribution name",
            "/dependencies",
        )
    lines = [
        _header(model).rstrip("\n"),
        "[build-system]",
        f'requires = ["setuptools=={SETUPTOOLS_VERSION}"]',
        'build-backend = "setuptools.build_meta"',
        "",
        "[project]",
        f"name = {json.dumps(target.distribution_name)}",
        f"version = {json.dumps(_version(target.version, target.package_key))}",
        f'requires-python = ">={target.minimum_python_version}"',
        "dependencies = [",
    ]
    for dependency in dependencies:
        interval = _dependency_interval(dependency.version, dependency.extension)
        lines.append(f"    {json.dumps(dependency.distribution_name + interval)},")
    lines.extend(
        (
            "]",
            "",
            "[project.urls]",
            f"Repository = {json.dumps(target.repository_url)}",
            "",
            "[tool.setuptools.packages.find]",
            'where = ["src"]',
            f"include = [{json.dumps(target.import_package)}, "
            f"{json.dumps(target.import_package + '.*')}]",
            "",
            "[tool.setuptools.package-data]",
            f"{json.dumps(target.import_package)} = "
            '["py.typed", "runtimeconditions.bindings.yaml"]',
            "",
        )
    )
    return "\n".join(lines)


def _type_construct(item: TypePlan) -> str:
    if item.kind == "object":
        return "object-construction"
    if item.kind == "enum":
        return "value-domain"
    assert item.expression is not None
    return {"array": "collection", "map": "map", "union": "union"}[item.expression.kind]


def _symbols(plan: EmissionPlan) -> list[dict[str, str]]:
    symbols: list[dict[str, str]] = []
    for coordinate, source_name in plan.any_coordinates:
        symbols.append(
            {
                "construct": "any",
                "coordinate": coordinate,
                "sourceName": source_name,
                "nativeName": "JSONValue",
                "file": "bindings.py",
            }
        )
    for declaration in plan.declarations:
        symbols.extend(
            (
                {
                    "construct": "declaration-call",
                    "coordinate": declaration.coordinate,
                    "sourceName": declaration.kind,
                    "nativeName": declaration.function,
                    "file": "bindings.py",
                },
                {
                    "construct": "marker-contract",
                    "coordinate": declaration.coordinate,
                    "sourceName": declaration.kind,
                    "nativeName": declaration.protocol,
                    "file": "bindings.py",
                },
            )
        )
    for imported_declaration in plan.imported_declarations:
        symbols.append(
            {
                "construct": "imported-marker-contract",
                "coordinate": imported_declaration.coordinate,
                "sourceName": imported_declaration.kind,
                "nativeName": imported_declaration.protocol,
            }
        )
    for item in plan.types:
        symbols.append(
            {
                "construct": _type_construct(item),
                "coordinate": item.coordinate,
                "sourceName": item.source_name,
                "nativeName": item.name,
                "file": "bindings.py",
            }
        )
        for field in item.fields:
            symbols.append(
                {
                    "construct": "field",
                    "coordinate": field.coordinate,
                    "sourceName": field.source_name,
                    "nativeName": field.name,
                    "parent": item.name,
                    "file": "bindings.py",
                }
            )
            if field.default_none:
                symbols.append(
                    {
                        "construct": "omitted-optional",
                        "coordinate": field.coordinate,
                        "sourceName": field.source_name,
                        "nativeName": field.name,
                        "parent": item.name,
                        "file": "bindings.py",
                    }
                )
        if item.kind == "enum":
            for member, value in item.members:
                symbols.append(
                    {
                        "construct": "value-member",
                        "coordinate": item.coordinate
                        + ":"
                        + json.dumps(value, ensure_ascii=False),
                        "sourceName": value,
                        "nativeName": member,
                        "parent": item.name,
                        "file": "bindings.py",
                    }
                )
        if item.kind == "alias" and item.expression is not None:
            if item.expression.kind == "array":
                symbols.append(
                    {
                        "construct": "collection-element",
                        "coordinate": item.coordinate,
                        "sourceName": item.source_name,
                        "nativeName": item.name,
                        "file": "bindings.py",
                    }
                )
            elif item.expression.kind == "map":
                symbols.append(
                    {
                        "construct": "map-entry",
                        "coordinate": item.coordinate,
                        "sourceName": item.source_name,
                        "nativeName": item.name,
                        "file": "bindings.py",
                    }
                )
    return sorted(
        symbols,
        key=lambda item: (
            item["coordinate"],
            item["construct"],
            item["nativeName"],
            item.get("parent", ""),
        ),
    )


def _manifest(plan: EmissionPlan, model: dict[str, Any]) -> str:
    document = {
        "apiVersion": "runtimeconditions.io/bindings/v1alpha1",
        "kind": "RuntimeConditionsBindingManifest",
        "generated": {
            "nonEditable": True,
            "emitter": EMITTER_NAME,
            "version": EMITTER_VERSION,
        },
        "model": {
            "apiVersion": model["apiVersion"],
            "semanticSha256": plan.model_digest,
        },
        "extension": {
            "id": model["rootExtension"]["id"],
            "semanticSha256": model["rootExtension"]["semanticSha256"],
        },
        "package": {
            "language": "python",
            "coordinate": plan.target.distribution_name,
            "name": plan.target.import_package,
            "minimumPythonVersion": plan.target.minimum_python_version,
        },
        "symbols": _symbols(plan),
    }
    return _header(model) + yaml.safe_dump(
        document, sort_keys=False, allow_unicode=True, default_flow_style=False
    )


def render_resources(plan: EmissionPlan, model: dict[str, Any]) -> dict[str, str]:
    """Render package metadata and resources without writing an output tree."""
    if (
        model["metadata"]["semanticSha256"] != plan.model_digest
        or model["rootExtension"]["id"] != plan.target.root_extension
    ):
        fail("model", "RCP1003", "model", "emission plan does not match supplied model")
    prefix = f"src/{plan.target.import_package}"
    return {
        "pyproject.toml": _pyproject(plan, model),
        f"{prefix}/py.typed": "",
        f"{prefix}/runtimeconditions.bindings.yaml": _manifest(plan, model),
    }
